events{}


http{

    upstream backend {
        server gateway1:8000;
        server gateway2:8000;
    }

    server{
        listen 80;
        location /{
            # return 200 "Hello from nginx Anshu";
            proxy_pass http://backend;

        }
    }
}